
import * as React from 'react';
import Card from '@mui/material/Card';
import MenuIcon from '@mui/icons-material/Menu';
import AppBar from '@mui/material/AppBar';
import IconButton from '@mui/material/IconButton';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar'
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Head from 'next/head';
import Image from 'next/image';
import salmonPic from '../imgs/salmon.png';
import reverseSalmon from '../imgs/reversesalmon.png';
import cutter from '../imgs/cutter.jpeg';
import fish from '../imgs/fish.jpg';
import cookie from '../imgs/frosted-cookie.jpg'
import shirt from '../imgs/shirt.jpg'
import family from '../imgs/family.jpg'
import styles from '../styles/Home.module.css';
import Form from './form';
import TableData from './table'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Salmon Cookies</title>
        <meta name="description" content="Generated by create next app" />
       
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
        <Image src={salmonPic} alt="salmon" width={180} height={64} />
          Pat's Salmon Cookies
					<Image src={reverseSalmon} alt="salmon" width={180} height={64} />
        </h1>

				<>
				<h2 className={styles.locationTitle}>Locations</h2>
				<h3>Open 6am to 7pm local</h3>
				</>
<div className = {styles.locations}>
	<div>
    <Card className = {styles.locationCard} sx={{ minWidth: 275 }}>
      <CardContent>
        <Typography variant="h5" component="div">
          Seattle
        </Typography>
        <Typography variant="body2">
          300 Salmon Street,
					<br></br>
					Seattle, USA
        </Typography>
      </CardContent>
      <CardActions>
        <Button size="small">Learn More</Button>
      </CardActions>
    </Card>
	</div>

	<div>
    <Card className = {styles.locationCard} sx={{ minWidth: 275 }}>
      <CardContent>
        <Typography variant="h5" component="div">
          Tokyo
        </Typography>
        <Typography variant="body2">
          300 Salmon Street,
					<br></br>
					Tokyo, Japan
        </Typography>
      </CardContent>
      <CardActions>
        <Button size="small">Learn More</Button>
      </CardActions>
    </Card>
	</div>

	<div>
    <Card className = {styles.locationCard} sx={{ minWidth: 275 }}>
      <CardContent>
        <Typography variant="h5" component="div">
          Dubai
        </Typography>
        <Typography variant="body2">
          300 Salmon Street,
					<br></br>
					Dubai, UAE
        </Typography>
      </CardContent>
      <CardActions>
        <Button size="small">Learn More</Button>
      </CardActions>
    </Card>
	</div>

	<div>
    <Card className = {styles.locationCard} sx={{ minWidth: 275 }}>
      <CardContent>
        <Typography variant="h5" component="div">
          Paris
        </Typography>
        <Typography variant="body2">
          300 Salmon Street,
					<br></br>
					Paris, France
        </Typography>
      </CardContent>
      <CardActions>
        <Button size="small">Learn More</Button>
      </CardActions>
    </Card>
	</div>

	<div>
    <Card className = {styles.locationCard} sx={{ minWidth: 275 }}>
      <CardContent>
        <Typography variant="h5" component="div">
          Lima
        </Typography>
        <Typography variant="body2">
          300 Salmon Street,
					<br></br>
					Lima, Peru
        </Typography>
      </CardContent>
      <CardActions>
        <Button size="small">Learn More</Button>
      </CardActions>
    </Card>
	</div>		
</div>
		<section className ={styles.contact}>
			<div className = {styles.contactInfo}>
				<h2 className = {styles.contactInfo}>Contact Us!</h2>
				<p className = {styles.contactInfo}>Pat Angler </p>
        <p className = {styles.contactInfo}> 555-555-5555 </p>
				<p className = {styles.contactInfo}>pangler@patssalmoncookes.com
				</p>
			</div>
			<article className = {styles.images}>
				<Image src={shirt} alt="a shirt with a fish" width={140} height={140} />

				<Image src={cookie} alt="a frosted cookie" width={140} height={140} />

				<Image src={fish} alt="a group of fish" width={140} height={140} />

				<Image src={cutter} alt="a fish cookie cutter" width={140} height={140} />
			</article>
		</section>

		<section className = {styles.about}>
			<Image src={family} alt="the founding family" width={360} height={180} />
				<article>
					<h2>Meet the Team</h2>
					<p className = {styles.story}>
						Starting in the great city of Seattle in 2009, Pat's Salmon Cookies is proof that dreams do come true. Pat
						spend much of the 2000's perfecting his recipe. Figuring out a way to make cookies and fish combine to make
						something delicious had never been done before and for good reason, it's not easy. But Pat, with his
						relentless pursuit of perfection, continued until he found the perfect recipe that you know and love today.
						Thanks for choosing Pat's Salmon Cookies.
					</p>
				</article>
		</section>
				<Form />

    <TableData />


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
           
          </span>
        </a>
      </footer>
    </div>
  )
}
